//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YakeenService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class Yakeen4ELMXFault
    {
        
        private CommonErrorObject commonErrorObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public CommonErrorObject commonErrorObject
        {
            get
            {
                return this.commonErrorObjectField;
            }
            set
            {
                this.commonErrorObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class CommonErrorObject
    {
        
        private string typeField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class gccInfoByNINResult
    {
        
        private string dateOfBirthHField;
        
        private string entryDateField;
        
        private string familyNameField;
        
        private string fatherNameField;
        
        private string firstNameField;
        
        private string grandFatherNameField;
        
        private int lifeStatusCodeField;
        
        private int logIdField;
        
        private string nationalityDescField;
        
        private string passportExpiryDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dateOfBirthH
        {
            get
            {
                return this.dateOfBirthHField;
            }
            set
            {
                this.dateOfBirthHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string entryDate
        {
            get
            {
                return this.entryDateField;
            }
            set
            {
                this.entryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string familyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fatherName
        {
            get
            {
                return this.fatherNameField;
            }
            set
            {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string grandFatherName
        {
            get
            {
                return this.grandFatherNameField;
            }
            set
            {
                this.grandFatherNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int lifeStatusCode
        {
            get
            {
                return this.lifeStatusCodeField;
            }
            set
            {
                this.lifeStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int logId
        {
            get
            {
                return this.logIdField;
            }
            set
            {
                this.logIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nationalityDesc
        {
            get
            {
                return this.nationalityDescField;
            }
            set
            {
                this.nationalityDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string passportExpiryDate
        {
            get
            {
                return this.passportExpiryDateField;
            }
            set
            {
                this.passportExpiryDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class gccInfoByNINRequest
    {
        
        private string chargeCodeField;
        
        private string gccNINField;
        
        private short gccNationalityField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode
        {
            get
            {
                return this.chargeCodeField;
            }
            set
            {
                this.chargeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gccNIN
        {
            get
            {
                return this.gccNINField;
            }
            set
            {
                this.gccNINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public short gccNationality
        {
            get
            {
                return this.gccNationalityField;
            }
            set
            {
                this.gccNationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", ConfigurationName="YakeenService.Yakeen4ELMX")]
    public interface Yakeen4ELMX
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(YakeenService.Yakeen4ELMXFault), Action="", Name="Yakeen4ELMXFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YakeenService.getGCCInfoByNINResponse> getGCCInfoByNINAsync(YakeenService.getGCCInfoByNIN request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(YakeenService.Yakeen4ELMXFault), Action="", Name="Yakeen4ELMXFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YakeenService.getEstablishmentInfoByMainIdResponse> getEstablishmentInfoByMainIdAsync(YakeenService.getEstablishmentInfoByMainId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(YakeenService.Yakeen4ELMXFault), Action="", Name="Yakeen4ELMXFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YakeenService.getAlienInfoByIqamaResponse> getAlienInfoByIqamaAsync(YakeenService.getAlienInfoByIqama request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(YakeenService.Yakeen4ELMXFault), Action="", Name="Yakeen4ELMXFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YakeenService.getCitizenInfoResponse> getCitizenInfoAsync(YakeenService.getCitizenInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGCCInfoByNIN", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getGCCInfoByNIN
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.gccInfoByNINRequest GCCInfoByNINRequest;
        
        public getGCCInfoByNIN()
        {
        }
        
        public getGCCInfoByNIN(YakeenService.gccInfoByNINRequest GCCInfoByNINRequest)
        {
            this.GCCInfoByNINRequest = GCCInfoByNINRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGCCInfoByNINResponse", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getGCCInfoByNINResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.gccInfoByNINResult GCCInfoByNINResult;
        
        public getGCCInfoByNINResponse()
        {
        }
        
        public getGCCInfoByNINResponse(YakeenService.gccInfoByNINResult GCCInfoByNINResult)
        {
            this.GCCInfoByNINResult = GCCInfoByNINResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class establishmentInfoByMainIdRequest
    {
        
        private string chargeCodeField;
        
        private string clientIpAddressField;
        
        private long establishmentIdField;
        
        private bool establishmentIdFieldSpecified;
        
        private double operatorIdField;
        
        private bool operatorIdFieldSpecified;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode
        {
            get
            {
                return this.chargeCodeField;
            }
            set
            {
                this.chargeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientIpAddress
        {
            get
            {
                return this.clientIpAddressField;
            }
            set
            {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long establishmentId
        {
            get
            {
                return this.establishmentIdField;
            }
            set
            {
                this.establishmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool establishmentIdSpecified
        {
            get
            {
                return this.establishmentIdFieldSpecified;
            }
            set
            {
                this.establishmentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double operatorId
        {
            get
            {
                return this.operatorIdField;
            }
            set
            {
                this.operatorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorIdSpecified
        {
            get
            {
                return this.operatorIdFieldSpecified;
            }
            set
            {
                this.operatorIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class establishmentInfoByMainIdResult
    {
        
        private string cRExpiryDateField;
        
        private string cRIssueDateField;
        
        private long faxField;
        
        private bool faxFieldSpecified;
        
        private int logIdField;
        
        private long mainCRNumberField;
        
        private bool mainCRNumberFieldSpecified;
        
        private long telephoneField;
        
        private bool telephoneFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CRExpiryDate
        {
            get
            {
                return this.cRExpiryDateField;
            }
            set
            {
                this.cRExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CRIssueDate
        {
            get
            {
                return this.cRIssueDateField;
            }
            set
            {
                this.cRIssueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool faxSpecified
        {
            get
            {
                return this.faxFieldSpecified;
            }
            set
            {
                this.faxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int logId
        {
            get
            {
                return this.logIdField;
            }
            set
            {
                this.logIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long mainCRNumber
        {
            get
            {
                return this.mainCRNumberField;
            }
            set
            {
                this.mainCRNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mainCRNumberSpecified
        {
            get
            {
                return this.mainCRNumberFieldSpecified;
            }
            set
            {
                this.mainCRNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telephoneSpecified
        {
            get
            {
                return this.telephoneFieldSpecified;
            }
            set
            {
                this.telephoneFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstablishmentInfoByMainId", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getEstablishmentInfoByMainId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.establishmentInfoByMainIdRequest EstablishmentInfoByMainIdRequest;
        
        public getEstablishmentInfoByMainId()
        {
        }
        
        public getEstablishmentInfoByMainId(YakeenService.establishmentInfoByMainIdRequest EstablishmentInfoByMainIdRequest)
        {
            this.EstablishmentInfoByMainIdRequest = EstablishmentInfoByMainIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstablishmentInfoByMainIdResponse", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getEstablishmentInfoByMainIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.establishmentInfoByMainIdResult EstablishmentInfoByMainIdResult;
        
        public getEstablishmentInfoByMainIdResponse()
        {
        }
        
        public getEstablishmentInfoByMainIdResponse(YakeenService.establishmentInfoByMainIdResult EstablishmentInfoByMainIdResult)
        {
            this.EstablishmentInfoByMainIdResult = EstablishmentInfoByMainIdResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class alienInfoByIqamaRequest
    {
        
        private string alienDateOfBirthHField;
        
        private string chargeCodeField;
        
        private string iqamaNumberField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alienDateOfBirthH
        {
            get
            {
                return this.alienDateOfBirthHField;
            }
            set
            {
                this.alienDateOfBirthHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string chargeCode
        {
            get
            {
                return this.chargeCodeField;
            }
            set
            {
                this.chargeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string iqamaNumber
        {
            get
            {
                return this.iqamaNumberField;
            }
            set
            {
                this.iqamaNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class alienInfoByIqamaResult
    {
        
        private string dateOfBirthHField;
        
        private string englishFirstNameField;
        
        private string englishLastNameField;
        
        private string englishSecondNameField;
        
        private string englishThirdNameField;
        
        private string firstNameField;
        
        private gender genderField;
        
        private bool genderFieldSpecified;
        
        private string iqamaExpiryDateHField;
        
        private string lastNameField;
        
        private lifeStatus lifeStatusField;
        
        private bool lifeStatusFieldSpecified;
        
        private int logIdField;
        
        private short nationalityCodeField;
        
        private string occupationDescField;
        
        private string passportExpiryDateField;
        
        private string passportNumberField;
        
        private string secondNameField;
        
        private string sponsorMoiNumberField;
        
        private string sponsorNameField;
        
        private string thirdNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dateOfBirthH
        {
            get
            {
                return this.dateOfBirthHField;
            }
            set
            {
                this.dateOfBirthHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string englishFirstName
        {
            get
            {
                return this.englishFirstNameField;
            }
            set
            {
                this.englishFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string englishLastName
        {
            get
            {
                return this.englishLastNameField;
            }
            set
            {
                this.englishLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string englishSecondName
        {
            get
            {
                return this.englishSecondNameField;
            }
            set
            {
                this.englishSecondNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string englishThirdName
        {
            get
            {
                return this.englishThirdNameField;
            }
            set
            {
                this.englishThirdNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public gender gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified
        {
            get
            {
                return this.genderFieldSpecified;
            }
            set
            {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string iqamaExpiryDateH
        {
            get
            {
                return this.iqamaExpiryDateHField;
            }
            set
            {
                this.iqamaExpiryDateHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public lifeStatus lifeStatus
        {
            get
            {
                return this.lifeStatusField;
            }
            set
            {
                this.lifeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lifeStatusSpecified
        {
            get
            {
                return this.lifeStatusFieldSpecified;
            }
            set
            {
                this.lifeStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int logId
        {
            get
            {
                return this.logIdField;
            }
            set
            {
                this.logIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public short nationalityCode
        {
            get
            {
                return this.nationalityCodeField;
            }
            set
            {
                this.nationalityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string occupationDesc
        {
            get
            {
                return this.occupationDescField;
            }
            set
            {
                this.occupationDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string passportExpiryDate
        {
            get
            {
                return this.passportExpiryDateField;
            }
            set
            {
                this.passportExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string passportNumber
        {
            get
            {
                return this.passportNumberField;
            }
            set
            {
                this.passportNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string secondName
        {
            get
            {
                return this.secondNameField;
            }
            set
            {
                this.secondNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string sponsorMoiNumber
        {
            get
            {
                return this.sponsorMoiNumberField;
            }
            set
            {
                this.sponsorMoiNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string sponsorName
        {
            get
            {
                return this.sponsorNameField;
            }
            set
            {
                this.sponsorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string thirdName
        {
            get
            {
                return this.thirdNameField;
            }
            set
            {
                this.thirdNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public enum gender
    {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        U,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public enum lifeStatus
    {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        U,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByIqama", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByIqama
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.alienInfoByIqamaRequest AlienInfoByIqamaRequest;
        
        public getAlienInfoByIqama()
        {
        }
        
        public getAlienInfoByIqama(YakeenService.alienInfoByIqamaRequest AlienInfoByIqamaRequest)
        {
            this.AlienInfoByIqamaRequest = AlienInfoByIqamaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByIqamaResponse", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByIqamaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.alienInfoByIqamaResult AlienInfoByIqamaResult;
        
        public getAlienInfoByIqamaResponse()
        {
        }
        
        public getAlienInfoByIqamaResponse(YakeenService.alienInfoByIqamaResult AlienInfoByIqamaResult)
        {
            this.AlienInfoByIqamaResult = AlienInfoByIqamaResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class citizenInfoRequest
    {
        
        private string chargeCodeField;
        
        private string dateOfBirthHField;
        
        private string ninField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode
        {
            get
            {
                return this.chargeCodeField;
            }
            set
            {
                this.chargeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateOfBirthH
        {
            get
            {
                return this.dateOfBirthHField;
            }
            set
            {
                this.dateOfBirthHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nin
        {
            get
            {
                return this.ninField;
            }
            set
            {
                this.ninField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/")]
    public partial class citizenInfoResult
    {
        
        private string dateOfBirthHField;
        
        private string englishFirstNameField;
        
        private string englishLastNameField;
        
        private string englishSecondNameField;
        
        private string englishThirdNameField;
        
        private string familyNameField;
        
        private string fatherNameField;
        
        private string firstNameField;
        
        private gender genderField;
        
        private bool genderFieldSpecified;
        
        private string grandFatherNameField;
        
        private string idExpiryDateField;
        
        private lifeStatus lifeStatusField;
        
        private bool lifeStatusFieldSpecified;
        
        private int logIdField;
        
        private string occupationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dateOfBirthH
        {
            get
            {
                return this.dateOfBirthHField;
            }
            set
            {
                this.dateOfBirthHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string englishFirstName
        {
            get
            {
                return this.englishFirstNameField;
            }
            set
            {
                this.englishFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string englishLastName
        {
            get
            {
                return this.englishLastNameField;
            }
            set
            {
                this.englishLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string englishSecondName
        {
            get
            {
                return this.englishSecondNameField;
            }
            set
            {
                this.englishSecondNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string englishThirdName
        {
            get
            {
                return this.englishThirdNameField;
            }
            set
            {
                this.englishThirdNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string familyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fatherName
        {
            get
            {
                return this.fatherNameField;
            }
            set
            {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public gender gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified
        {
            get
            {
                return this.genderFieldSpecified;
            }
            set
            {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string grandFatherName
        {
            get
            {
                return this.grandFatherNameField;
            }
            set
            {
                this.grandFatherNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string idExpiryDate
        {
            get
            {
                return this.idExpiryDateField;
            }
            set
            {
                this.idExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public lifeStatus lifeStatus
        {
            get
            {
                return this.lifeStatusField;
            }
            set
            {
                this.lifeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lifeStatusSpecified
        {
            get
            {
                return this.lifeStatusFieldSpecified;
            }
            set
            {
                this.lifeStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int logId
        {
            get
            {
                return this.logIdField;
            }
            set
            {
                this.logIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string occupationCode
        {
            get
            {
                return this.occupationCodeField;
            }
            set
            {
                this.occupationCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitizenInfo", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getCitizenInfo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.citizenInfoRequest CitizenInfoRequest;
        
        public getCitizenInfo()
        {
        }
        
        public getCitizenInfo(YakeenService.citizenInfoRequest CitizenInfoRequest)
        {
            this.CitizenInfoRequest = CitizenInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitizenInfoResponse", WrapperNamespace="http://yakeen4elmx.yakeen.elm.com/", IsWrapped=true)]
    public partial class getCitizenInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4elmx.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YakeenService.citizenInfoResult CitizenInfoResult;
        
        public getCitizenInfoResponse()
        {
        }
        
        public getCitizenInfoResponse(YakeenService.citizenInfoResult CitizenInfoResult)
        {
            this.CitizenInfoResult = CitizenInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface Yakeen4ELMXChannel : YakeenService.Yakeen4ELMX, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class Yakeen4ELMXClient : System.ServiceModel.ClientBase<YakeenService.Yakeen4ELMX>, YakeenService.Yakeen4ELMX
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Yakeen4ELMXClient() : 
                base(Yakeen4ELMXClient.GetDefaultBinding(), Yakeen4ELMXClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Yakeen4ELMXPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Yakeen4ELMXClient(EndpointConfiguration endpointConfiguration) : 
                base(Yakeen4ELMXClient.GetBindingForEndpoint(endpointConfiguration), Yakeen4ELMXClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Yakeen4ELMXClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Yakeen4ELMXClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Yakeen4ELMXClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Yakeen4ELMXClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Yakeen4ELMXClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YakeenService.getGCCInfoByNINResponse> YakeenService.Yakeen4ELMX.getGCCInfoByNINAsync(YakeenService.getGCCInfoByNIN request)
        {
            return base.Channel.getGCCInfoByNINAsync(request);
        }
        
        public System.Threading.Tasks.Task<YakeenService.getGCCInfoByNINResponse> getGCCInfoByNINAsync(YakeenService.gccInfoByNINRequest GCCInfoByNINRequest)
        {
            YakeenService.getGCCInfoByNIN inValue = new YakeenService.getGCCInfoByNIN();
            inValue.GCCInfoByNINRequest = GCCInfoByNINRequest;
            return ((YakeenService.Yakeen4ELMX)(this)).getGCCInfoByNINAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YakeenService.getEstablishmentInfoByMainIdResponse> YakeenService.Yakeen4ELMX.getEstablishmentInfoByMainIdAsync(YakeenService.getEstablishmentInfoByMainId request)
        {
            return base.Channel.getEstablishmentInfoByMainIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<YakeenService.getEstablishmentInfoByMainIdResponse> getEstablishmentInfoByMainIdAsync(YakeenService.establishmentInfoByMainIdRequest EstablishmentInfoByMainIdRequest)
        {
            YakeenService.getEstablishmentInfoByMainId inValue = new YakeenService.getEstablishmentInfoByMainId();
            inValue.EstablishmentInfoByMainIdRequest = EstablishmentInfoByMainIdRequest;
            return ((YakeenService.Yakeen4ELMX)(this)).getEstablishmentInfoByMainIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YakeenService.getAlienInfoByIqamaResponse> YakeenService.Yakeen4ELMX.getAlienInfoByIqamaAsync(YakeenService.getAlienInfoByIqama request)
        {
            return base.Channel.getAlienInfoByIqamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<YakeenService.getAlienInfoByIqamaResponse> getAlienInfoByIqamaAsync(YakeenService.alienInfoByIqamaRequest AlienInfoByIqamaRequest)
        {
            YakeenService.getAlienInfoByIqama inValue = new YakeenService.getAlienInfoByIqama();
            inValue.AlienInfoByIqamaRequest = AlienInfoByIqamaRequest;
            return ((YakeenService.Yakeen4ELMX)(this)).getAlienInfoByIqamaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YakeenService.getCitizenInfoResponse> YakeenService.Yakeen4ELMX.getCitizenInfoAsync(YakeenService.getCitizenInfo request)
        {
            return base.Channel.getCitizenInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YakeenService.getCitizenInfoResponse> getCitizenInfoAsync(YakeenService.citizenInfoRequest CitizenInfoRequest)
        {
            YakeenService.getCitizenInfo inValue = new YakeenService.getCitizenInfo();
            inValue.CitizenInfoRequest = CitizenInfoRequest;
            return ((YakeenService.Yakeen4ELMX)(this)).getCitizenInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Yakeen4ELMXPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Yakeen4ELMXPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.205/Yakeen4ELMX/Yakeen4ELMX");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Yakeen4ELMXClient.GetBindingForEndpoint(EndpointConfiguration.Yakeen4ELMXPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Yakeen4ELMXClient.GetEndpointAddress(EndpointConfiguration.Yakeen4ELMXPort);
        }
        
        public enum EndpointConfiguration
        {
            
            Yakeen4ELMXPort,
        }
    }
}
